# Generated by Django 5.1.7 on 2025-03-22 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farm_core", "0005_user_npop_certificate_expiry_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "strength",
                    models.IntegerField(
                        default=1,
                        help_text="Higher value means stronger recommendation",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "primary_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations_as_primary",
                        to="farm_core.product",
                    ),
                ),
                (
                    "recommended_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations_as_secondary",
                        to="farm_core.product",
                    ),
                ),
            ],
            options={
                "ordering": ["-strength"],
                "unique_together": {("primary_product", "recommended_product")},
            },
        ),
    ]
